/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author UsuarioLocal
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdReportes = new javax.swing.JTabbedPane();
        ifrmVentas = new javax.swing.JInternalFrame();
        ifrmIngresos = new javax.swing.JInternalFrame();
        ifrmProductos = new javax.swing.JInternalFrame();
        ifrmInventario = new javax.swing.JInternalFrame();
        ifrmReportes = new javax.swing.JInternalFrame();
        ifrmCuadreDiario = new javax.swing.JInternalFrame();
        ifrmConfiguracion = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Inventarios y Ventas");

        ifrmVentas.setVisible(true);

        javax.swing.GroupLayout ifrmVentasLayout = new javax.swing.GroupLayout(ifrmVentas.getContentPane());
        ifrmVentas.getContentPane().setLayout(ifrmVentasLayout);
        ifrmVentasLayout.setHorizontalGroup(
            ifrmVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ifrmVentasLayout.setVerticalGroup(
            ifrmVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tbdReportes.addTab("VENTAS", ifrmVentas);

        ifrmIngresos.setVisible(true);

        javax.swing.GroupLayout ifrmIngresosLayout = new javax.swing.GroupLayout(ifrmIngresos.getContentPane());
        ifrmIngresos.getContentPane().setLayout(ifrmIngresosLayout);
        ifrmIngresosLayout.setHorizontalGroup(
            ifrmIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ifrmIngresosLayout.setVerticalGroup(
            ifrmIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tbdReportes.addTab("INGRESOS", ifrmIngresos);

        ifrmProductos.setVisible(true);

        javax.swing.GroupLayout ifrmProductosLayout = new javax.swing.GroupLayout(ifrmProductos.getContentPane());
        ifrmProductos.getContentPane().setLayout(ifrmProductosLayout);
        ifrmProductosLayout.setHorizontalGroup(
            ifrmProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ifrmProductosLayout.setVerticalGroup(
            ifrmProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tbdReportes.addTab("PRODUCTOS", ifrmProductos);

        ifrmInventario.setVisible(true);

        javax.swing.GroupLayout ifrmInventarioLayout = new javax.swing.GroupLayout(ifrmInventario.getContentPane());
        ifrmInventario.getContentPane().setLayout(ifrmInventarioLayout);
        ifrmInventarioLayout.setHorizontalGroup(
            ifrmInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ifrmInventarioLayout.setVerticalGroup(
            ifrmInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tbdReportes.addTab("INVENTARIO", ifrmInventario);

        ifrmReportes.setVisible(true);

        javax.swing.GroupLayout ifrmReportesLayout = new javax.swing.GroupLayout(ifrmReportes.getContentPane());
        ifrmReportes.getContentPane().setLayout(ifrmReportesLayout);
        ifrmReportesLayout.setHorizontalGroup(
            ifrmReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ifrmReportesLayout.setVerticalGroup(
            ifrmReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tbdReportes.addTab("REPORTES", ifrmReportes);

        ifrmCuadreDiario.setVisible(true);

        javax.swing.GroupLayout ifrmCuadreDiarioLayout = new javax.swing.GroupLayout(ifrmCuadreDiario.getContentPane());
        ifrmCuadreDiario.getContentPane().setLayout(ifrmCuadreDiarioLayout);
        ifrmCuadreDiarioLayout.setHorizontalGroup(
            ifrmCuadreDiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ifrmCuadreDiarioLayout.setVerticalGroup(
            ifrmCuadreDiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tbdReportes.addTab("CUADRE DIARIO", ifrmCuadreDiario);

        ifrmConfiguracion.setVisible(true);

        javax.swing.GroupLayout ifrmConfiguracionLayout = new javax.swing.GroupLayout(ifrmConfiguracion.getContentPane());
        ifrmConfiguracion.getContentPane().setLayout(ifrmConfiguracionLayout);
        ifrmConfiguracionLayout.setHorizontalGroup(
            ifrmConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ifrmConfiguracionLayout.setVerticalGroup(
            ifrmConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tbdReportes.addTab("CONFIGURACION", ifrmConfiguracion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame ifrmConfiguracion;
    private javax.swing.JInternalFrame ifrmCuadreDiario;
    private javax.swing.JInternalFrame ifrmIngresos;
    private javax.swing.JInternalFrame ifrmInventario;
    private javax.swing.JInternalFrame ifrmProductos;
    private javax.swing.JInternalFrame ifrmReportes;
    private javax.swing.JInternalFrame ifrmVentas;
    private javax.swing.JTabbedPane tbdReportes;
    // End of variables declaration//GEN-END:variables
}
